import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Influencers AI Insights</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to
          <br/>
          Instagram Influencers
          <br/>
          AI Insights
        </h1>
        <h2 className={styles.subtitle}>
          Featuring a lot of if/else statements posing as Machine Learning
        </h2>

        <h3 className={styles.subsubtitle}>Top Influencers by category</h3>
        <table>
          <thead>
          <tr>
            <th>Influencer</th>
            <th>Category</th>
            <th>Followers</th>
          </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
        <br/>
        <br/>
        <h3 className={styles.subsubtitle}>Top Influencers by country</h3>
        <table>
          <thead>
          <tr>
            <th>Influencer</th>
            <th>Country</th>
            <th>Followers</th>
          </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
        <br/>
      </main>
    </div>
  )
}

export default Home
